config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mpi_cbs.mediforms.urls')),
]

mpi_cbs/mediforms/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.urls import include, path, register_converter

from mpi_cbs.mediforms import views


class MethodConverter:
    regex = 'mrt|mrtbegleitung|tms'

    def to_python(self, value):
        return value

    def to_url(self, value):
        return value


register_converter(MethodConverter, 'method')


urlpatterns = [
    path('login/', LoginView.as_view(template_name='mediforms/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path(r'i18n/', include('django.conf.urls.i18n')),

    path('mediforms/', include([
        path('', views.Index.as_view(), name='index'),

        path('form/<uuid:token>/', views.FormView.as_view(), name='form'),
        path(
            'success/',
            TemplateView.as_view(template_name='mediforms/success.html'),
            name='success',
        ),

        path(
            'mrt/erklaerung-datenspeicherung-und-nutzung/',
            TemplateView.as_view(template_name='mediforms/pages/data_protection_declaration_mrt.html'),
            name='data-protection-declaration-mrt',
        ),
        path(
            'mrtbegleitung/erklaerung-datenspeicherung-und-nutzung/',
            TemplateView.as_view(template_name='mediforms/pages/data_protection_declaration_mrtbegleitung.html'),
            name='data-protection-declaration-mrtbegleitung',
        ),
        path(
            '<method:method>/einwilligung-datenspeicherung/',
            views.DataStorageConsentView.as_view(),
            name='data-storage-consent',
        ),
        path(
            '<method:method>/einwilligung-untersuchung/',
            TemplateView.as_view(template_name='mediforms/pages/exploration_consent.html'),
            name='exploration-consent',
        ),
        path(
            '<method:method>/informationtext/',
            TemplateView.as_view(template_name='mediforms/pages/information_text.html'),
            name='information-text',
        ),

        path('tokens/', views.TokenListView.as_view(), name='token-list'),
    ])),
]

mpi_cbs/mediforms/models.py
import re
import string
import unicodedata
from uuid import uuid4

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _


def sanitize_string(_string):
    # replace umlauts
    _string = re.sub('[ä]', 'ae', _string)
    _string = re.sub('[Ä]', 'Ae', _string)
    _string = re.sub('[ö]', 'oe', _string)
    _string = re.sub('[Ö]', 'Oe', _string)
    _string = re.sub('[ü]', 'ue', _string)
    _string = re.sub('[Ü]', 'Ue', _string)
    _string = re.sub('[ß]', 'ss', _string)

    # remove accents
    _string = ''.join(c for c in unicodedata.normalize('NFKD', _string)
                      if not unicodedata.combining(c))

    # remove punctuation
    _string = _string.translate(str.maketrans('', '', string.punctuation))

    return _string


class YesNoField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 3
        kwargs['choices'] = (
            ('yes', _('yes')),
            ('no', _('no')),
        )
        super().__init__(*args, **kwargs)


class Method(models.Model):
    key = models.CharField(_('Key'), max_length=16, primary_key=True)
    name = models.CharField(_('Name'), max_length=64)
    color = models.CharField(_('Color'), max_length=8, default='#0070c0')

    def __str__(self):
        return self.name

    class Meta:
        ordering = 'name',


class Token(models.Model):
    id = models.UUIDField(_('ID'), default=uuid4, primary_key=True)
    method = models.ForeignKey(Method, on_delete=models.PROTECT, verbose_name=_('Method'))
    pseudonym = models.CharField(_('Pseudonym'), max_length=64)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                                   verbose_name=_('Created by'))

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = '-created_at',
        unique_together = 'method', 'pseudonym'
        verbose_name = 'Token'
        verbose_name_plural = 'Tokens'


class PersonalData(models.Model):
    class Gender(models.TextChoices):
        FEMALE = 'f', _('Female')
        MALE = 'm', _('Male')
        DIVERSE = 'd', _('Diverse')

    last_name = models.CharField(_('Last name'), max_length=255)
    first_name = models.CharField(_('First name'), max_length=255)

    height = models.IntegerField(_('Height'), null=True, blank=True)
    weight = models.IntegerField(_('Weight'), null=True, blank=True)

    date_of_birth = models.DateField(_('Date of birth'))
    birthplace = models.CharField(_('Birthplace'), max_length=255, null=True, blank=True)

    gender = models.CharField(_('Gender'), max_length=1, choices=Gender.choices, null=True, blank=True)

    street = models.CharField(_('Street'), max_length=255, null=True, blank=True)
    zip_code = models.CharField(_('Zip code'), max_length=5, null=True, blank=True)
    city = models.CharField(_('City'), max_length=255, null=True, blank=True)

    phone_number = models.CharField(_('Phone number'), max_length=20, null=True, blank=True)
    mobile_number = models.CharField(_('Mobile number'), max_length=20, null=True, blank=True)
    email = models.EmailField(_('E-mail'), blank=True, default='')

    class Meta:
        abstract = True


class QuestionsWomen(models.Model):
    schwanger = YesNoField(_('schwanger'), null=True, blank=True)

    class Meta:
        abstract = True


class QuestionsWomenMRT(QuestionsWomen):
    spirale = YesNoField(_('spirale'), null=True, blank=True)

    class Meta:
        abstract = True


class QuestionsMRT(models.Model):
    fehlsicht = YesNoField(_('fehlsicht'))
    kontaktlinsen = YesNoField(_('kontaktlinsen'))
    brille = YesNoField(_('brille'))
    astigmatismus = YesNoField(_('astigmatismus'))
    klaustrophobie = YesNoField(_('klaustrophobie'))
    geraeusch = YesNoField(_('geraeusch'))
    tinnitus = YesNoField(_('tinnitus'))
    operationen = YesNoField(_('operationen'))
    operationenwelchewann = models.TextField(_('operationenwelchewann'), blank=True, default='')
    metallclips = YesNoField(_('metallclips'))
    metallplatten = YesNoField(_('metallplatten'))
    gelenkprothesen = YesNoField(_('gelenkprothesen'))
    stent = YesNoField(_('stent'))
    herzschrittmacher = YesNoField(_('herzschrittmacher'))
    herzklappen = YesNoField(_('herzklappen'))
    innenohrimplantate = YesNoField(_('innenohrimplantate'))
    shunt = YesNoField(_('shunt'))
    hirnschrittmacher = YesNoField(_('hirnschrittmacher'))
    medikamentenpumpe = YesNoField(_('medikamentenpumpe'))
    metallsplitter = YesNoField(_('metallsplitter'))
    metalljob = YesNoField(_('metalljob'))
    metalleintrag = YesNoField(_('metalleintrag'))
    metallteile = YesNoField(_('metallteile'))
    metallteilewas = models.TextField(_('metallteilewas'), blank=True, default='')
    tattoos = YesNoField(_('tattoos'))
    tattoosort = models.TextField(_('tattoosort'), blank=True, default='')
    nikotinpflaster = YesNoField(_('nikotinpflaster'))
    rueckenlage = YesNoField(_('rueckenlage'))
    medikamente = YesNoField(_('medikamente'))
    medikamentewelche = models.TextField(_('medikamentewelche'), blank=True, default='')
    neuro = YesNoField(_('neuro'))
    neurowelche = models.TextField(_('neurowelche'), blank=True, default='')
    kopfverletzung = YesNoField(_('kopfverletzung'))
    kopfwelche = models.TextField(_('kopfwelche'), blank=True, default='')
    epilepsie = YesNoField(_('epilepsie'))
    herzrhythmus = YesNoField(_('herzrhythmus'))
    herzkrank = YesNoField(_('herzkrank'))
    durchblutung = YesNoField(_('durchblutung'))
    atemwege = YesNoField(_('atemwege'))
    allergie = YesNoField(_('allergie'))
    allergiewelche = models.TextField(_('allergiewelche'), blank=True, default='')
    niere = YesNoField(_('niere'))
    mrt12 = YesNoField(_('mrt12'))
    mrtanzahl = models.PositiveIntegerField(_('mrtanzahl'))

    class Meta:
        abstract = True


class QuestionsTMS(models.Model):
    epilepsie = YesNoField(_('epilepsie'))
    fieberkrampf = YesNoField(_('fieberkrampf'))
    familieepilepsie = YesNoField(_('familieepilepsie'))
    bewusstlosigkeit = YesNoField(_('bewusstlosigkeit'))
    kopfschmerzen = YesNoField(_('kopfschmerzen'))
    migraene = YesNoField(_('migraene'))
    schlafstoerung = YesNoField(_('schlafstoerung'))
    drogen = YesNoField(_('drogen'))
    medikamente = YesNoField(_('medikamente'))
    medikamentewelche = models.TextField(_('medikamentewelche'), blank=True, default='')
    neuro = YesNoField(_('neuro'))
    neurowelche = models.TextField(_('neurowelche'), blank=True, default='')
    psycho = YesNoField(_('psycho'))
    psychowelche = models.TextField(_('psychowelche'), blank=True, default='')
    kopfverletzung = YesNoField(_('kopfverletzung'))
    kopfwelche = models.TextField(_('kopfwelche'), blank=True, default='')
    operationen = YesNoField(_('operationen'))
    operationenwelchewann = models.TextField(_('operationenwelchewann'), blank=True, default='')
    metallclips = YesNoField(_('metallclips'))
    metallplatten = YesNoField(_('metallplatten'))
    gelenkprothesen = YesNoField(_('gelenkprothesen'))
    stent = YesNoField(_('stent'))
    herzschrittmacher = YesNoField(_('herzschrittmacher'))
    herzklappen = YesNoField(_('herzklappen'))
    innenohrimplantate = YesNoField(_('innenohrimplantate'))
    shunt = YesNoField(_('shunt'))
    hirnschrittmacher = YesNoField(_('hirnschrittmacher'))
    medikamentenpumpe = YesNoField(_('medikamentenpumpe'))
    metallsplitter = YesNoField(_('metallsplitter'))
    metalljob = YesNoField(_('metalljob'))
    metalleintrag = YesNoField(_('metalleintrag'))
    herzrhythmus = YesNoField(_('herzrhythmus'))
    herzkrank = YesNoField(_('herzkrank'))
    durchblutung = YesNoField(_('durchblutung'))
    atemwege = YesNoField(_('atemwege'))
    hauterkrankungen = YesNoField(_('hauterkrankungen'), null=True)
    narben = YesNoField(_('narben'), null=True)

    class Meta:
        abstract = True


class FormData(models.Model):
    pseudonym = models.CharField(_('Pseudonym'), max_length=64, editable=False)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    token_created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                                         verbose_name=_('Token created by'))

    class Meta:
        abstract = True


class AbstractFormDataMRT(FormData, PersonalData, QuestionsMRT, QuestionsWomenMRT):
    class Meta:
        abstract = True


class FormDataMRT(AbstractFormDataMRT):
    class Meta:
        ordering = 'last_name', 'first_name', 'date_of_birth'
        verbose_name = _('Form data MRT')
        verbose_name_plural = _('Form data MRT')


class FormDataMRTBegleitung(AbstractFormDataMRT):
    class Meta:
        ordering = 'last_name', 'first_name', 'date_of_birth'
        verbose_name = _('Form data MRT Begleitung')
        verbose_name_plural = _('Form data MRT Begleitung')


class FormDataTMS(FormData, PersonalData, QuestionsTMS, QuestionsWomen):
    class Meta:
        ordering = 'last_name', 'first_name', 'date_of_birth'
        verbose_name = _('Form data TMS')
        verbose_name_plural = _('Form data TMS')


class PDFRenderingJob(models.Model):
    method = models.ForeignKey(Method, on_delete=models.PROTECT)
    content_type = models.ForeignKey(ContentType, on_delete=models.PROTECT)
    object_id = models.PositiveIntegerField()
    form_data = GenericForeignKey('content_type', 'object_id')
    language = models.CharField(_('Language'), max_length=8, default='de')

    class Meta:
        verbose_name = _('PDF rendering job')
        verbose_name_plural = _('PDF rendering jobs')


class PDF(models.Model):
    def get_upload_path(self, filename):

mpi_cbs/mediforms/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import urlencode
from django.views import generic
from django.views.decorators.cache import never_cache

from mpi_cbs.mediforms.forms import (ConsentAgreementForm,
                                     MRTForm, MRTBegleitungForm, PersonalDataForm,
                                     QuestionsMRTForm, QuestionsTMSForm,
                                     QuestionsWomenForm, QuestionsWomenMRTForm,
                                     TMSForm, TokenForm)
from mpi_cbs.mediforms.models import PDFRenderingJob, Token


def get_questions_form_classes(method):
    if method.startswith('mrt'):
        return dict(general=QuestionsMRTForm, women=QuestionsWomenMRTForm)
    elif method == 'tms':
        return dict(general=QuestionsTMSForm, women=QuestionsWomenForm)


class Index(LoginRequiredMixin, generic.FormView):
    form_class = TokenForm
    template_name = 'mediforms/index.html'

    def get_context_data(self):
        context_data = super().get_context_data()
        context_data['method'] = self.request.GET.get('method', '')
        context_data['token'] = self.request.GET.get('token', '')
        return context_data

    def post(self, request, *args, **kwargs):
        token, _created = Token.objects.get_or_create(
            method_id=request.POST.get('method'),
            pseudonym=request.POST.get('pseudonym'),
            defaults=dict(created_by=self.request.user),
        )
        params = urlencode(dict(
            token=token.id,
            method=token.method,
        ))
        return HttpResponseRedirect('{}?{}'.format(reverse('index'), params))


class TokenListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'tokens'
    model = Token
    template_name = 'mediforms/token_list.html'


@method_decorator(never_cache, name='dispatch')
class FormView(generic.FormView):
    success_url = reverse_lazy('success')

    def dispatch(self, request, *args, **kwargs):
        self.token = get_object_or_404(Token, pk=kwargs.get('token'))
        return super().dispatch(request, *args, **kwargs)

    def get_template_names(self):
        return [f'mediforms/pages/form_{self.token.method.key}.html']

    def get_context_data(self, **kwargs):
        questions_form_classes = get_questions_form_classes(self.token.method.key)

        context = super().get_context_data(**kwargs)
        context['method'] = self.token.method
        form_data = None if self.request.method == 'GET' else self.request.POST
        context['personal_data_form'] = PersonalDataForm(form_data)
        context['questions_form'] = questions_form_classes['general'](form_data, initial={'mrtanzahl': 0})
        context['questions_form_women'] = questions_form_classes['women'](form_data)
        context['consent_agreement_form'] = ConsentAgreementForm()

        return context

    def get_form_class(self):
        method = self.token.method.key
        if method == 'mrt':
            return MRTForm
        elif method == 'mrtbegleitung':
            return MRTBegleitungForm
        elif method == 'tms':
            return TMSForm

    def form_valid(self, form):
        form_data = form.save(commit=False)
        form_data.pseudonym = self.token.pseudonym
        form_data.token_created_by = self.token.created_by
        form_data.save()

        PDFRenderingJob.objects.create(
            method=self.token.method,
            form_data=form_data,
            language=self.request.LANGUAGE_CODE,
        )

        self.token.delete()

        return super().form_valid(form)


class DataStorageConsentView(generic.TemplateView):
    template_name = 'mediforms/pages/data_storage_consent.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        method = self.kwargs.get('method')
        if method.startswith('mrt'):
            context['method'] = 'MRT'
        elif method == 'tms':
            context['method'] = 'TMS/tDCS'
        return context

mpi_cbs/mediforms/templates/mediforms/pdfs/mrt.html
{% extends "mediforms/pdfs/pdf.html" %}

{% load i18n %}


{% block body %}
<div class="ui container">
  <h1>{% blocktranslate %}Magnetresonanz-Tomographie (MRT){% endblocktranslate %}</h1>

  {% include "mediforms/includes/information_text_mrt.html" %}
</div>


<div class="ui container" style="page-break-before: always;">
  <p style="text-align: center; border: 2px solid black; padding: 5px;">
    <b>{% blocktranslate %}Fragebogen zur Person und zu Kontraindikationen im Rahmen der Studie{% endblocktranslate %}</b><br>
    <span class="h3">{% blocktranslate %}Magnetresonanz-Tomographie (MRT){% endblocktranslate %}</span>
  </p>

  <table>
    <tr>
      <th>{{ form.last_name.label_tag }}</th>
      <td>{{ form_data.last_name }}</td>
      <th>{{ form.first_name.label_tag }}</th>
      <td>{{ form_data.first_name }}</td>
      <th>{{ form.height.label_tag }}</th>
      <td>{{ form_data.height|default_if_none:"" }} cm</td>
    </tr>
    <tr>
      <th>{{ form.date_of_birth.label_tag }}</th>
      <td>{{ form_data.date_of_birth }}</td>
      <th>{{ form.birthplace.label_tag }}</th>
      <td>{{ form_data.birthplace|default_if_none:"" }}</td>
      <th>{{ form.weight.label_tag }}</th>
      <td>{{ form_data.weight|default_if_none:"" }} kg</td>
    </tr>
    <tr>
      <th>{{ form.gender.label_tag }}</th>
      <td>{{ form_data.get_gender_display|default_if_none:"" }}</td>
      <td colspan="4"></td>
    </tr>
    <tr>
      <th>{{ form.street.label_tag }}</th>
      <td>{{ form_data.street|default_if_none:"" }}</td>
      <th>{{ form.zip_code.label_tag }}</th>
      <td>{{ form_data.zip_code|default_if_none:"" }}</td>
      <th>{{ form.city.label_tag }}</th>
      <td>{{ form_data.city|default_if_none:"" }}</td>
    </tr>
    <tr>
      <th>{{ form.phone_number.label_tag }}</th>
      <td>{{ form_data.phone_number|default_if_none:"" }}</td>
      <th>{{ form.mobile_number.label_tag }}</th>
      <td>{{ form_data.mobile_number|default_if_none:"" }}</td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <th>{{ form.email.label_tag }}</th>
      <td>{{ form_data.email }}</td>
      <td colspan="4"></td>
    </tr>
  </table>

  <table style="width: 80%">
    {% for field in questions_form %}
    <tr>
      <td>{{ forloop.counter }}. {{ field.label_tag }}</td>
      <td>
        {% if field.field.widget.input_type == "radio" %}
        {% trans field.value %}
        {% else %}
        {{ field.value }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}

    <tr>
      <td colspan="2"><i style="font-size: 15px">{% blocktranslate %}NUR FÜR VERSUCHSTEILNEHMERINNEN:{% endblocktranslate %}</i></td>
    </tr>

    {% for field in questions_form_women %}
    <tr>
      <td>{{ field.label_tag }}</td>
      <td>{% if field.value %}{% trans field.value %}{% endif %}</td>
    </tr>
    {% endfor %}
  </table>

  <p style="margin-top: 30px">{% blocktranslate %}Wenn Sie etwas nicht verstanden haben oder zusätzliche Informationen benötigen, geben wir Ihnen gerne nähere Auskünfte im Gespräch. Bitte fragen Sie uns nach allem, was Ihnen wichtig erscheint.{% endblocktranslate %}</p>
</div>


<div class="ui container" style="page-break-before: always;">
{% include "mediforms/includes/iup.html" %}
</div>


<div class="ui container" style="page-break-before: always;">
{% include "mediforms/includes/data_protection_declaration_mrt.html" %}
</div>


{% include "mediforms/includes/exploration_consent_mrt.html" %}


{% endblock body %}

mpi_cbs/mediforms/templates/mediforms/pdfs/mrtbegleitung.html
{% extends "mediforms/pdfs/pdf.html" %}

{% load i18n %}


{% block body %}
<div class="ui container">
  <h1>{% blocktranslate %}Magnetresonanz-Untersuchung für Begleitpersonen{% endblocktranslate %}</h1>

  {% include "mediforms/includes/information_text_mrtbegleitung.html" %}
</div>


<div class="ui container" style="page-break-before: always;">
  <p style="text-align: center; border: 2px solid black; padding: 5px;">
    <b>{% blocktranslate %}Fragebogen zur Person und zu Kontraindikationen im Rahmen der Studie{% endblocktranslate %}</b><br>
    <span>{% blocktranslate %}Magnetresonanz-Untersuchung für Begleitpersonen{% endblocktranslate %}</span>
  </p>

  <table>
    <tr>
      <th>{{ form.last_name.label_tag }}</th>
      <td>{{ form_data.last_name }}</td>
      <th>{{ form.first_name.label_tag }}</th>
      <td>{{ form_data.first_name }}</td>
      <th>{{ form.height.label_tag }}</th>
      <td>{{ form_data.height|default_if_none:"" }}</td>
    </tr>
    <tr>
      <th>{{ form.date_of_birth.label_tag }}</th>
      <td>{{ form_data.date_of_birth }}</td>
      <th>{{ form.birthplace.label_tag }}</th>
      <td>{{ form_data.birthplace|default_if_none:"" }}</td>
      <th>{{ form.weight.label_tag }}</th>
      <td>{{ form_data.weight|default_if_none:"" }}</td>
    </tr>
    <tr>
      <th>{{ form.gender.label_tag }}</th>
      <td>{{ form_data.get_gender_display|default_if_none:"" }}</td>
      <td colspan="4"></td>
    </tr>
    <tr>
      <th>{{ form.street.label_tag }}</th>
      <td>{{ form_data.street|default_if_none:"" }}</td>
      <th>{{ form.zip_code.label_tag }}</th>
      <td>{{ form_data.zip_code|default_if_none:"" }}</td>
      <th>{{ form.city.label_tag }}</th>
      <td>{{ form_data.city|default_if_none:"" }}</td>
    </tr>
    <tr>
      <th>{{ form.phone_number.label_tag }}</th>
      <td>{{ form_data.phone_number|default_if_none:"" }}</td>
      <th>{{ form.mobile_number.label_tag }}</th>
      <td>{{ form_data.mobile_number|default_if_none:"" }}</td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <th>{{ form.email.label_tag }}</th>
      <td>{{ form_data.email }}</td>
      <td colspan="4"></td>
    </tr>
  </table>

  <table style="width: 75%">
    {% for field in questions_form %}
    <tr>
      <td>{{ forloop.counter }}. {{ field.label_tag }}</td>
      <td>
        {% if field.field.widget.input_type == "radio" %}
        {% trans field.value %}
        {% else %}
        {{ field.value }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}

    <tr>
      <td colspan="2"><i style="font-size: 15px;">{% blocktranslate %}NUR FÜR VERSUCHSTEILNEHMERINNEN:{% endblocktranslate %}</i></td>
    </tr>

    {% for field in questions_form_women %}
    <tr>
      <td>{{ field.label_tag }}</td>
      <td>{% if field.value %}{% trans field.value %}{% endif %}</td>
    </tr>
    {% endfor %}
  </table>
</div>


<div class="ui container" style="page-break-before: always;">
{% include "mediforms/includes/iup.html" %}
</div>


<div class="ui container" style="page-break-before: always;">
{% include "mediforms/includes/exploration_consent_mrtbegleitung.html" %}
</div>


<div class="ui container" style="page-break-before: always;">
{% include "mediforms/includes/data_storage_and_usage_consent_mrtbegleitung.html" %}
</div>

{% endblock body %}

mpi_cbs/mediforms/templates/mediforms/pdfs/pdf.html
{% extends "mediforms/base.html" %}


{% block extra_styles %}
@page {
  size: A4;
}

body {
  font-size: 10.9px;
}

h1 {font-size: 18px; color: {{ method.color }};}
h2 {font-size: 15px; color: {{ method.color }};}
h3 {font-size: 13px; color: {{ method.color }};}

span.h3 {
  color: {{ method.color }};
  font-weight: bolder;
}

.six.wide.column {
  font-size: 9px;
}
{% endblock extra_styles %}